webtalk_init -webtalk_dir G:\\Vivado\\project_newadderintegrator\\project_newadderintegrator.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-02-12 14:21:17" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "618a6033972p4plhpu342do7fj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.508 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1549957967617" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1549957967617"
webtalk_add_data -client sdk -key uid -value "1549959773069" -context "sdk\\\\bsp/1549959773069"
webtalk_add_data -client sdk -key hwid -value "1549957967617" -context "sdk\\\\bsp/1549959773069"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1549959773069"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1549959773069"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1549959773069"
webtalk_add_data -client sdk -key uid -value "1549959788658" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key hwid -value "1549957967617" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key bspid -value "1549959773069" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key projSize -value "195.15625" -context "sdk\\\\application/1549959788658"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1549961476846"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1549961476846"
webtalk_transmit -clientid 2348212282 -regid "" -xml G:\\Vivado\\project_newadderintegrator\\project_newadderintegrator.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html G:\\Vivado\\project_newadderintegrator\\project_newadderintegrator.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm G:\\Vivado\\project_newadderintegrator\\project_newadderintegrator.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
